'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Inventor_Pipe.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _45gr_ELBOW_PVC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("45gr_ELBOW_PVC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _45grELBOW_HDPE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("45grELBOW_HDPE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _45grELBOW_STAINLESS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("45grELBOW_STAINLESS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _45grELBOW_STEEL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("45grELBOW_STEEL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ADAPTOR_REDUCING_BUSH_PVC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ADAPTOR_REDUCING_BUSH_PVC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BLIND_FLANG_STEEL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BLIND_FLANG_STEEL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BLIND_FLANGE_HDPE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BLIND_FLANGE_HDPE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BLIND_FLANGE_STAINLESS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BLIND_FLANGE_STAINLESS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bolts88() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bolts88", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BoltsA2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BoltsA2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BRANCH_CONNECTION_STAINLESS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BRANCH_CONNECTION_STAINLESS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CAP_HDPE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CAP_HDPE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CAP_PVC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CAP_PVC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CAP_STAINLESS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CAP_STAINLESS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CAP_STEEL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CAP_STEEL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CONC_RED_HDPE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CONC_RED_HDPE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CONC_REDUCER_PVC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CONC_REDUCER_PVC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CONC_REDUCER_STAINLESS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CONC_REDUCER_STAINLESS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property COUPLING_PVC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("COUPLING_PVC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property COUPLING_STAINLESS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("COUPLING_STAINLESS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property COUPLING_STEEL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("COUPLING_STEEL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dammgulast() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dammgulast", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ECC_RED_HDPE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ECC_RED_HDPE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ECC_RED_STEEL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ECC_RED_STEEL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ECC_REDUCER_PVC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ECC_REDUCER_PVC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ECC_REDUCER_STAINLESS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ECC_REDUCER_STAINLESS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ELBOW_HDPE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ELBOW_HDPE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ELBOW_PVC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ELBOW_PVC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ELBOW_STAINLESS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ELBOW_STAINLESS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ELBOW_STEEL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ELBOW_STEEL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ELEC_COUPLING_HDPE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ELEC_COUPLING_HDPE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FEMALE_ADAPTER_HDPE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FEMALE_ADAPTER_HDPE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FLANGE_BLIND_PVC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FLANGE_BLIND_PVC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FLANGE_LJ_PVC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FLANGE_LJ_PVC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FLANGE_SW_PVC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FLANGE_SW_PVC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GasketEPDM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GasketEPDM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GasketNBR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GasketNBR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GasketPTFE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GasketPTFE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GasketSILICONE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GasketSILICONE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LJ_FLANG_STEEL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LJ_FLANG_STEEL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LJ_FLANGE_ALU() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LJ_FLANGE_ALU", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LJ_FLANGE_HDPE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LJ_FLANGE_HDPE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LJ_FLANGE_STAINLESS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LJ_FLANGE_STAINLESS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MALE_ADAPTER_HDPE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MALE_ADAPTER_HDPE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Male_Adaptor_PVC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Male_Adaptor_PVC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NIPPLE_STAINLESS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NIPPLE_STAINLESS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NIPPLE_STEEL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NIPPLE_STEEL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OLET_STAINLESS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OLET_STAINLESS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OLET_STEEL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OLET_STEEL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PIPE_HDPE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PIPE_HDPE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PIPE_PVC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PIPE_PVC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PIPE_STAINLESS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PIPE_STAINLESS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PIPE_STEEL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PIPE_STEEL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PipeClamp304L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PipeClamp304L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PipeClamp304L1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PipeClamp304L1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PipeClamp88() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PipeClamp88", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PipeClipASV() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PipeClipASV", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PipeClipGOEMA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PipeClipGOEMA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PULLED_TEE_STAINLESS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PULLED_TEE_STAINLESS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RED_STEEL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RED_STEEL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RED_TEE_HDPE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RED_TEE_HDPE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RED_TEE_PVC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RED_TEE_PVC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RED_TEE_STAINLESS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RED_TEE_STAINLESS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RED_TEE_STEEL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RED_TEE_STEEL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property REDUCING_BUSH_PVC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("REDUCING_BUSH_PVC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SO_FLANG_STEEL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SO_FLANG_STEEL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SO_FLANGE_STAINLESS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SO_FLANGE_STAINLESS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Stauff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stauff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property STUB_END_HDPE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("STUB_END_HDPE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property STUB_END_PVC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("STUB_END_PVC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property STUB_END_STAINLESS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("STUB_END_STAINLESS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property STUB_END_STEEL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("STUB_END_STEEL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StudBolts88() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StudBolts88", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StudBoltsA2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StudBoltsA2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TEE_HDPE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TEE_HDPE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TEE_PVC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TEE_PVC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TEE_STAINLESS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TEE_STAINLESS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TEE_STEEL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TEE_STEEL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UBolt88() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UBolt88", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UBolt881() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UBolt881", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UBoltA2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UBoltA2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UNION_HDPE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UNION_HDPE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UNION_PVC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UNION_PVC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UNION_STAINLESS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UNION_STAINLESS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UNION_STEEL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UNION_STEEL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WN_FLANG_STEEL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WN_FLANG_STEEL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WN_FLANGE_STAINLESS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WN_FLANGE_STAINLESS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
